// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoveUp.Context;

#nullable disable

namespace MoveUp.Infrastructure.Migrations
{
    [DbContext(typeof(MoveUpDbContext))]
    [Migration("20261002164542_PreserveExerciseIdentity")]
    partial class PreserveExerciseIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("MoveUp.Entities.AcompanhamentoConfig", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fuso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Inicio")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AcompanhamentoConfig", null, t =>
                        {
                            t.HasCheckConstraint("CK_Acompanhamento_Unico", "Id = 1");
                        });
                });

            modelBuilder.Entity("MoveUp.Entities.Exercicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("GrupoMuscular")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Exercicios", null, t =>
                        {
                            t.HasCheckConstraint("CK_Exercicio_Grupo", "length(trim(GrupoMuscular)) BETWEEN 1 AND 80");

                            t.HasCheckConstraint("CK_Exercicio_Nome", "length(trim(Nome)) BETWEEN 1 AND 120");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-4000-8000-000000000001"),
                            CreatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrupoMuscular = "Peito",
                            Nome = "Supino reto"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-4000-8000-000000000002"),
                            CreatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrupoMuscular = "Peito",
                            Nome = "Supino inclinado"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-4000-8000-000000000003"),
                            CreatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrupoMuscular = "Peito",
                            Nome = "Crucifixo"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-4000-8000-000000000004"),
                            CreatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrupoMuscular = "Costas",
                            Nome = "Puxada frontal"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-4000-8000-000000000005"),
                            CreatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrupoMuscular = "Costas",
                            Nome = "Remada baixa"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-4000-8000-000000000006"),
                            CreatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrupoMuscular = "Pernas",
                            Nome = "Agachamento"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-4000-8000-000000000007"),
                            CreatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrupoMuscular = "Pernas",
                            Nome = "Leg press"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-4000-8000-000000000008"),
                            CreatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrupoMuscular = "Pernas",
                            Nome = "Cadeira extensora"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-4000-8000-000000000009"),
                            CreatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrupoMuscular = "Bíceps",
                            Nome = "Rosca direta"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-4000-8000-000000000010"),
                            CreatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrupoMuscular = "Tríceps",
                            Nome = "Tríceps pulley"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-4000-8000-000000000011"),
                            CreatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrupoMuscular = "Ombros",
                            Nome = "Desenvolvimento"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-4000-8000-000000000012"),
                            CreatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrupoMuscular = "Abdômen",
                            Nome = "Abdominal"
                        });
                });

            modelBuilder.Entity("MoveUp.Entities.MetaRevisao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dias")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Inicio")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Inicio")
                        .IsUnique();

                    b.ToTable("MetaRevisoes", null, t =>
                        {
                            t.HasCheckConstraint("CK_Meta_Dias", "Dias BETWEEN 1 AND 7");
                        });
                });

            modelBuilder.Entity("MoveUp.Entities.RotinaRevisao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dias")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Inicio")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Inicio")
                        .IsUnique();

                    b.ToTable("RotinaRevisoes");
                });

            modelBuilder.Entity("MoveUp.Entities.SerieRealizada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Carga")
                        .HasColumnType("REAL");

                    b.Property<double>("CargaPlanejada")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("ConcluidaEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordem")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Repeticoes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RepeticoesPlanejadas")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessaoExercicioId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessaoExercicioId", "Ordem")
                        .IsUnique();

                    b.ToTable("SeriesRealizadas", null, t =>
                        {
                            t.HasCheckConstraint("CK_Serie_Planejamento", "Ordem >= 0 AND RepeticoesPlanejadas > 0 AND CargaPlanejada >= 0");

                            t.HasCheckConstraint("CK_Serie_Resultado", "(Status = 'concluida' AND Repeticoes IS NOT NULL AND Repeticoes > 0 AND Carga IS NOT NULL AND Carga >= 0 AND ConcluidaEm IS NOT NULL) OR (Status <> 'concluida' AND Repeticoes IS NULL AND Carga IS NULL AND ConcluidaEm IS NULL)");

                            t.HasCheckConstraint("CK_Serie_Status", "Status IN ('pendente', 'concluida', 'pulada')");
                        });
                });

            modelBuilder.Entity("MoveUp.Entities.SessaoExercicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ExercicioOrigemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("GrupoMuscular")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordem")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessaoTreinoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TempoDescanso")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SessaoTreinoId", "Ordem")
                        .IsUnique();

                    b.ToTable("SessaoExercicios", null, t =>
                        {
                            t.HasCheckConstraint("CK_SessaoExercicio_Descanso", "TempoDescanso >= 0");

                            t.HasCheckConstraint("CK_SessaoExercicio_Ordem", "Ordem >= 0");
                        });
                });

            modelBuilder.Entity("MoveUp.Entities.SessaoTreino", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DataPresenca")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Fim")
                        .HasColumnType("TEXT");

                    b.Property<string>("FusoPresenca")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeTreino")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TreinoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TreinoOrigemId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .IsUnique()
                        .HasFilter("Status = 'emAndamento'");

                    b.HasIndex("TreinoId");

                    b.HasIndex("Inicio", "Id");

                    b.HasIndex("Status", "DataPresenca");

                    b.ToTable("SessoesTreino", null, t =>
                        {
                            t.HasCheckConstraint("CK_Sessao_Fim", "(Status = 'emAndamento' AND Fim IS NULL) OR (Status <> 'emAndamento' AND Fim IS NOT NULL AND Fim >= Inicio)");

                            t.HasCheckConstraint("CK_Sessao_Nome", "length(trim(NomeTreino)) BETWEEN 1 AND 120");

                            t.HasCheckConstraint("CK_Sessao_Observacao", "Observacao IS NULL OR length(Observacao) <= 2000");

                            t.HasCheckConstraint("CK_Sessao_Status", "Status IN ('emAndamento', 'concluida', 'cancelada')");
                        });
                });

            modelBuilder.Entity("MoveUp.Entities.Treino", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DiaSemana");

                    b.ToTable("Treinos", null, t =>
                        {
                            t.HasCheckConstraint("CK_Treino_Dia", "DiaSemana BETWEEN 1 AND 7");

                            t.HasCheckConstraint("CK_Treino_Nome", "length(trim(Nome)) BETWEEN 1 AND 120");
                        });
                });

            modelBuilder.Entity("MoveUp.Entities.TreinoExercicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("CargaInicial")
                        .HasColumnType("REAL");

                    b.Property<Guid>("ExercicioId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordem")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Repeticoes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Series")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TempoDescanso")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TreinoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExercicioId");

                    b.HasIndex("TreinoId", "ExercicioId")
                        .IsUnique();

                    b.HasIndex("TreinoId", "Ordem")
                        .IsUnique();

                    b.ToTable("TreinoExercicios", null, t =>
                        {
                            t.HasCheckConstraint("CK_Item_Carga", "CargaInicial >= 0");

                            t.HasCheckConstraint("CK_Item_Descanso", "TempoDescanso >= 0");

                            t.HasCheckConstraint("CK_Item_Ordem", "Ordem >= 0");

                            t.HasCheckConstraint("CK_Item_Repeticoes", "Repeticoes > 0");

                            t.HasCheckConstraint("CK_Item_Series", "Series > 0");
                        });
                });

            modelBuilder.Entity("MoveUp.Entities.SerieRealizada", b =>
                {
                    b.HasOne("MoveUp.Entities.SessaoExercicio", "SessaoExercicio")
                        .WithMany("Series")
                        .HasForeignKey("SessaoExercicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SessaoExercicio");
                });

            modelBuilder.Entity("MoveUp.Entities.SessaoExercicio", b =>
                {
                    b.HasOne("MoveUp.Entities.SessaoTreino", "SessaoTreino")
                        .WithMany("Exercicios")
                        .HasForeignKey("SessaoTreinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SessaoTreino");
                });

            modelBuilder.Entity("MoveUp.Entities.SessaoTreino", b =>
                {
                    b.HasOne("MoveUp.Entities.Treino", "Treino")
                        .WithMany()
                        .HasForeignKey("TreinoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Treino");
                });

            modelBuilder.Entity("MoveUp.Entities.TreinoExercicio", b =>
                {
                    b.HasOne("MoveUp.Entities.Exercicio", "Exercicio")
                        .WithMany("TreinoExercicios")
                        .HasForeignKey("ExercicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MoveUp.Entities.Treino", "Treino")
                        .WithMany("TreinoExercicios")
                        .HasForeignKey("TreinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercicio");

                    b.Navigation("Treino");
                });

            modelBuilder.Entity("MoveUp.Entities.Exercicio", b =>
                {
                    b.Navigation("TreinoExercicios");
                });

            modelBuilder.Entity("MoveUp.Entities.SessaoExercicio", b =>
                {
                    b.Navigation("Series");
                });

            modelBuilder.Entity("MoveUp.Entities.SessaoTreino", b =>
                {
                    b.Navigation("Exercicios");
                });

            modelBuilder.Entity("MoveUp.Entities.Treino", b =>
                {
                    b.Navigation("TreinoExercicios");
                });
#pragma warning restore 612, 618
        }
    }
}
