// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoveUp.Context;

#nullable disable

namespace MoveUp.Infrastructure.Migrations
{
    [DbContext(typeof(MoveUpDbContext))]
    partial class MoveUpDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("MoveUp.Entities.Exercicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("GrupoMuscular")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Exercicios", null, t =>
                        {
                            t.HasCheckConstraint("CK_Exercicio_Grupo", "length(trim(GrupoMuscular)) BETWEEN 1 AND 80");

                            t.HasCheckConstraint("CK_Exercicio_Nome", "length(trim(Nome)) BETWEEN 1 AND 120");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-4000-8000-000000000001"),
                            CreatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrupoMuscular = "Peito",
                            Nome = "Supino reto"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-4000-8000-000000000002"),
                            CreatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrupoMuscular = "Peito",
                            Nome = "Supino inclinado"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-4000-8000-000000000003"),
                            CreatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrupoMuscular = "Peito",
                            Nome = "Crucifixo"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-4000-8000-000000000004"),
                            CreatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrupoMuscular = "Costas",
                            Nome = "Puxada frontal"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-4000-8000-000000000005"),
                            CreatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrupoMuscular = "Costas",
                            Nome = "Remada baixa"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-4000-8000-000000000006"),
                            CreatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrupoMuscular = "Pernas",
                            Nome = "Agachamento"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-4000-8000-000000000007"),
                            CreatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrupoMuscular = "Pernas",
                            Nome = "Leg press"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-4000-8000-000000000008"),
                            CreatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrupoMuscular = "Pernas",
                            Nome = "Cadeira extensora"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-4000-8000-000000000009"),
                            CreatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrupoMuscular = "Bíceps",
                            Nome = "Rosca direta"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-4000-8000-000000000010"),
                            CreatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrupoMuscular = "Tríceps",
                            Nome = "Tríceps pulley"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-4000-8000-000000000011"),
                            CreatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrupoMuscular = "Ombros",
                            Nome = "Desenvolvimento"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-4000-8000-000000000012"),
                            CreatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrupoMuscular = "Abdômen",
                            Nome = "Abdominal"
                        });
                });

            modelBuilder.Entity("MoveUp.Entities.Treino", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DiaSemana");

                    b.ToTable("Treinos", null, t =>
                        {
                            t.HasCheckConstraint("CK_Treino_Dia", "DiaSemana BETWEEN 1 AND 7");

                            t.HasCheckConstraint("CK_Treino_Nome", "length(trim(Nome)) BETWEEN 1 AND 120");
                        });
                });

            modelBuilder.Entity("MoveUp.Entities.TreinoExercicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("CargaInicial")
                        .HasColumnType("REAL");

                    b.Property<Guid>("ExercicioId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordem")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Repeticoes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Series")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TempoDescanso")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TreinoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExercicioId");

                    b.HasIndex("TreinoId", "ExercicioId")
                        .IsUnique();

                    b.HasIndex("TreinoId", "Ordem")
                        .IsUnique();

                    b.ToTable("TreinoExercicios", null, t =>
                        {
                            t.HasCheckConstraint("CK_Item_Carga", "CargaInicial >= 0");

                            t.HasCheckConstraint("CK_Item_Descanso", "TempoDescanso >= 0");

                            t.HasCheckConstraint("CK_Item_Ordem", "Ordem >= 0");

                            t.HasCheckConstraint("CK_Item_Repeticoes", "Repeticoes > 0");

                            t.HasCheckConstraint("CK_Item_Series", "Series > 0");
                        });
                });

            modelBuilder.Entity("MoveUp.Entities.TreinoExercicio", b =>
                {
                    b.HasOne("MoveUp.Entities.Exercicio", "Exercicio")
                        .WithMany("TreinoExercicios")
                        .HasForeignKey("ExercicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MoveUp.Entities.Treino", "Treino")
                        .WithMany("TreinoExercicios")
                        .HasForeignKey("TreinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercicio");

                    b.Navigation("Treino");
                });

            modelBuilder.Entity("MoveUp.Entities.Exercicio", b =>
                {
                    b.Navigation("TreinoExercicios");
                });

            modelBuilder.Entity("MoveUp.Entities.Treino", b =>
                {
                    b.Navigation("TreinoExercicios");
                });
#pragma warning restore 612, 618
        }
    }
}
